### ISSUE TITLE
[DOCS] Possible document drift on integration instructions

### ISSUE THREAD

**Issue by rromanchuk** [DataDog/datadog-trace-agent#509]
I noticed i've ended up with a configuration that might be related to document drift. I just recently looked at my config and realized there are different instructions.

Here is one of my current configurations

```yml
datadog_config:
  tags:
    - env:prod
    - role:worker
  apm_config:
    analyzed_spans:
      grape|grape.endpoint_run: 1
      sparcore|rack.request: 1
      net/http|http.request: 1
      aws|aws.command: 1
  apm_enabled: "true"
  logs_enabled: true
```

On https://docs.datadoghq.com/tracing/setup/#agent-configuration i see that to enable apm it's 

```yml
apm_config:
  enabled: true
```

but I have the `apm_enabled: "true"` at root level with the strange "true", i remember reading somewhere it was required, but i cant remember what doc I was reading.  I also noticed i have `analyzed_spans` which is completely missing on https://docs.datadoghq.com/tracing/setup/#agent-configuration I found them on https://app.datadoghq.com/apm/docs/trace-search

**Comment by gbbr** [comment]
> On https://docs.datadoghq.com/tracing/setup/#agent-configuration i see that to enable apm it's

This is the correct one to use.

> I also noticed i have analyzed_spans which is completely missing.

I'd assume this is missing because we were probably still experimenting with it at the time. I doubt it'll be added because we are in the process of implementing this in the client, meaning that you'll be able to tell the agent which spans to analyze via the tracer's API. This will make it a lot easier and more flexible to use this functionality (you won't need to edit the agent config or restart the agent). But for now, what you did is correct.

---

I'm not entirely sure what this issue is about 😊Is there anything that isn't working or is your question more of a curiosity?

**Comment by rromanchuk** [comment]
<img width="1596" alt="screen shot 2018-11-11 at 8 54 29 pm" src="https://user-images.githubusercontent.com/102188/48327518-0a286300-e5f4-11e8-9b7d-55f29e328042.png">

https://docs.datadoghq.com/tracing/setup/?tab=agent630#trace-search

Basically the above documentation is super confusing. It gets prime real estate in the console, and after integrating tracing, it feels like I missed a big step. It reads like "If you want trace search to work, you have to edit your agents with these settings"  It's also confusing because the syntax isn't explained, even though I can guess. 

The one at docs.datadoghq.com is even a bigger offender, service name i can guess, but everything else looks internal. Reader is just going to assume `1` is a `bool` for enabled/disabled, when really it's a float to control rate. Probably could use a little bit of explanation 
 
```yaml
apm_config:
  analyzed_spans:
    <SERVICE_NAME_1>|servlet.request: 1
    <SERVICE_NAME_2>|servlet.request: 1
```
